### ISSUE TITLE
Improve the api for submission of a form

### ISSUE THREAD

**Issue by Roonerelli** [heartysoft/restsharp.portable.hal#2]
Currently in order to submit a form we need to follow various links and then do a GetAsync to return the form. Then prior to submission of the form we need to rewalk those same links followed in the get

This can be mitigated to a certain extent by caching

However, it should be possible to improve the api by adding another method such as GetFormForSubmission that returns an Action<> that allows the posting of the data to be deffered

**Comment by ashic** [comment]
The F# API supports this in a way. If you do GetAsync(), you get back a resource, that you can Follow() and submit. The C# wrapper seems to be missing a few methods. 

We should do a couple of things:

* Add the Resource() return capability to the C# wrapper.
* Allow submission on a Resource via self link (likely no impact on performance or network calls). Would be convenient.
* Add method to return a strongly typed resource. Currently, doing a GetAsync<T>() deserializes the data to type T. This is what's preventing chaining for the submission.

**Comment by ashic** [comment]
Changes made:
* RequestContext can't Post / Put / Delete anymore.
* Resource now allows Post / Put / Delete.

The hidden get before post is no longer there. You GetAsync() a resource. Can use the data. And can PostAsync(newData). newData doesn't need to be of the same type (it can be a different class with fewer properties). It can also be an anonymous object. It gets merged with contents of the resource.

Object serialisation uses JSON.NET. Case conversions for submittable data don't happen automatically. If camel casing is needed, change the default serialisation settings.

**Comment by Roonerelli** [comment]
Awesome ;-)
